version: '3.1'
services:
    db:
        image: postgres
        restart: always
        environment:
            POSTGRES_USER: turgyn
            POSTGRES_PASSWORD: turgyn
            POSTGRES_DB: komek
        ports:
            - 5432:5432

    app:
        build: .
        depends_on:
            - db
        ports:
            - 8080:8080
        environment:
            - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/komek
